version: '3.7'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: root
      MONGODB_DATABASE: notification
      MONGODB_PASS: password
    volumes:
      - db:/data/db
  backend:
    image: notificationbackend
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_PORT=27017
    build:
      context: .
      # dockerfile: Dockerfile
      target: development
    ports:
      - 3001:3000
    depends_on:
      - db
    command: npm run start:debug
    # restart: always
networks:
  webnet:
volumes:
  db:
